.PHONY: clean All

All:
	@echo "----------Building project:[ Delta_Robot_Reference - Debug ]----------"
	@$(MAKE) -f  "Delta_Robot_Reference.mk"
clean:
	@echo "----------Cleaning project:[ Delta_Robot_Reference - Debug ]----------"
	@$(MAKE) -f  "Delta_Robot_Reference.mk" clean
